package:
  name: adh_v45_mul
  version: "4.5"

source:
  git_url: https://github.com/jejabour/adhtesting.git

target_platform:
  - win-64

requirements:
  build:
     - setuptools

about:
  home: https://github.com/jejabour/adhtesting
