package:
  name: adh_v45_win64
  version: "4.5"

source:
  git_url: https://github.com/jejabour/adhtestingrevised.git

target_platform:
  - win-64

requirements:
  build:
     - setuptools


about:
  home: https://github.com/jejabour/adhtestingrevised
