package:
  name: adh_V5.0-WIN64
  version: "5.0"

source:
  git_url: https://github.com/jejabour/adhtestingrevised.git

target_platform:
  - win-64

requirements:
  build:
     - setuptools

about:
  home: https://github.com/jejabour/adhtestingrevised
